<?php

return [

    // Landing
    'home' => 'Home',
    'tutorial' => 'Tutorial',
    'aboutme' => 'About Me',
    'roadmap' => 'Roadmap',
    'signIn' => 'Sign In',
    'signUp' => 'Sign Up',
    'realTimeSim' => 'Real-Time Management Simulator',
    'demand' => 'Demand',
    'demandTxt' => 'Each airport has its own demand and simulated passengers based on the route\'s destination and origin',
    'multiplayer' => 'Multiplayer',
    'multiplayerTxt' => 'The world where you manage your airline is in constant competition with other players, affecting the demand for your flights and your revenue',
    'free' => 'Free',
    'freeTxt' => 'This project is designed to be 100% free with no ads, microtransactions, or pay-to-win mechanics. The project is fully funded by user donations',
    'monopoly' => 'Monopoly',
    'monopolyTxt' => 'Use unethical techniques against other players to become the top-rated airline',
    'start' => 'START YOUR AIRLINE HERE',
    'register' => 'Register',
    'changelog' => 'Changelog',
    'showMore' => 'Show more',
    'showLess' => 'Show less',

    // Landing / Infotext
    'infoText1' => '<h3>Manage your fleet</h3>
              <p>
                Take full control of your fleet: manage routes, set ticket prices, and keep your aircraft in top condition.
              </p>
              <p>
                Choose from over 30 aircraft models and access more than 350 airports worldwide to design routes that fit your airline\'s needs.
              </p>
              <p>
                Purchase second-hand planes in a dynamic, ever-evolving market.
              </p>
              <p>
                Your airline operates in a world influenced by supply and demand generated by other players. Adapt to stay competitive!
              </p>',
    'infoText2' => '<h3>Compete with other players</h3>
              <p>
                Face off against other players in a dynamic market. Adjust your routes based on demand to maximize your profits.
              </p>
              <p>
                Implement strategies to dominate key routes, outperform competitors, and secure your position in the market.
              </p>
              <p>
                Check the rankings page to see your airline\'s position and earn exclusive rewards for reaching and maintaining the Top 1 spot.
              </p>',


    // Footer
    'developedBy' => 'Developed by Carlos Oliva Aznar',
    'aboutMe' => 'About Me',
    'blog' => 'Blog',
    'contactMe' => 'Contact Me',
    'info' => 'Information',
    'donate' => 'Donate',
    'discord' => 'Discord',
    'tutorial' => 'Tutorial',
    'additionalInfo' => 'Additional Information',
    'termns' => 'Terms and Conditions',
    'privacy' => 'Privacy Policy',
    'roadmap' => 'Roadmap',

    // About Me
    'who' => 'Who am I?',
    'whoT1' => 'I am Carlos Oliva, a software developer from Spain. I was born in Zaragoza, where I completed my studies. I did bachelor in Social Sciences and later completed two superior technician degrees, one in multiplatform application development and another in web application development. Despite my baccalaureate teachers\' doubts, I managed to complete both higher degrees with very good grades.',
    'whoT2' => 'Since I was 9 years old, I have had a great passion for aviation, allowing me at a very young age to know how to pilot different aircraft in simulators or in real life with remote-controlled vehicles like drones or planes (I have crashed a few). Like many who share this hobby, I am in the last stage before I can consider becoming an airline pilot, I only need to save 80,000 euros. God willing, I will win the lottery, or I might have to sell a kidney to some mafia in Belarus.',
    'whoT3' => 'I created this application as a final project for my superior technician degree in web application development. It is my approach to what I believe a management application should be: free, without ads, premium currencies, or traps to make people spend money on a video game.',
    'whoT4' => 'Keep in mind that I am still learning day by day and I am not perfect. The application may have flaws or may not be tailored to your needs. If there is something that can be improved, I welcome suggestions and advice for improvement.',

    'objt' => 'What is my objective?',
    'objtT1' => 'I have always been a big fan of management games, partly because of my father who let me play Zoo Tycoon 2 and Dino Island when I was 3 years old. I have tried different aviation management games, but I never found one that fully convinced me, as they all had microtransactions or premium currencies that ruined the gaming experience. Some even blocked the game after a few hours, forcing you to pay to continue playing.',
    'objtT2' => 'Because of these games, I always had the idea of creating a game of the same style without having to spend real money on every action you had to take.',
    'objtT3' => 'For this reason, and because I have to submit a final project, I decided to make my idea a reality.',
    'objtT4' => 'The game is entirely self-funded, and I will not include ads or microtransactions in the application. If you want to support, it is completely voluntary and can be done in the "donate" section ',
    'objtDonate' => 'donate',

    // Donate
    'accessDonate' => 'Click to access the PayPal donations page',
    'thanks' => 'Thank you very much!',
    'donateT1' => 'Really, thank you from the bottom of my heart. This project is entirely funded by donations, which means that every contribution greatly helps to continue developing and improving this application. Every little gesture of support is deeply appreciated and significantly contributes to ensuring that we can continue offering you new content and constant updates.',
    'donateT2' => 'If you have found the application useful and wish to support my work, I cordially invite you to consider making a donation. Any amount, however modest, will be received with sincere gratitude and will be used to further enhance the experience on our platform.',
    'donateT3' => 'Additionally, if you want to get to know me better and discover who is behind this project, I encourage you to visit the',
    'donateT4' => 'section on our website. And to stay updated on all the news and updates, I invite you to join our',
    'discordServer' => 'Discord Server',
    'donateT5' => ', where you can interact with other users, share your suggestions and opinions, and have an exclusive role if you have donated, allowing you to learn about updates before anyone else and have exclusive access to future updates.',
    'donateT6' => 'Once again, I want to express my deepest gratitude for your continued support and for being an active part of this wonderful community. Thank you for believing in this project and for contributing to its growth and success!',

    // Roadmap
    'roadMap' => 'Road Map',

    'version2' => 'V-0.2.0',
    'version2txt' => 'Real-time simulation implementation and basic gameplay mechanics for the initial game operations.',

    'version4' => 'V-0.4.0',
    'version4txt' => 'Economic update: aircraft leasing system, loan options, stock trading among players, and the addition of government subsidies.',

    'version6' => 'V-0.6.0',
    'version6txt' => 'Introduction of player alliances, including group chats and the creation of airline groups for a collaborative experience.',

    'version10' => 'V-1.0.0',
    'version10txt' => 'Full and stable version of the game, with all mechanics optimized and ready for official release.',

    'version3' => 'V-0.3.0',
    'version3txt' => 'Multiplayer mode implementation with supply and demand calculations, random events, and limited resources in the environment.',

    'version5' => 'V-0.5.0',
    'version5txt' => 'Company status simulation, introduction of customer opinions, handling contracts, and passenger service options.',

    'version7' => 'V-0.7.0',
    'version7txt' => 'Incorporation of cargo transport, dynamic price simulation, and adjustments in buying and selling according to market demand.',

    'versionx' => 'V-X.X.X',
    'versionxtxt' => 'Coming soon...',

];

// Plantilla
// '' => '',
// {{ __('landing.') }}
